# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newProjectWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1128, 799)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 140, 141, 51))
        self.label.setObjectName("label")
        self.ProjectNameEdit = QtWidgets.QLineEdit(Form)
        self.ProjectNameEdit.setGeometry(QtCore.QRect(240, 150, 311, 41))
        self.ProjectNameEdit.setObjectName("ProjectNameEdit")
        self.ProjectAddressEdit = QtWidgets.QLineEdit(Form)
        self.ProjectAddressEdit.setGeometry(QtCore.QRect(460, 250, 541, 41))
        self.ProjectAddressEdit.setObjectName("ProjectAddressEdit")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(80, 260, 108, 24))
        self.label_2.setObjectName("label_2")
        self.ProjectAddressBtn = QtWidgets.QPushButton(Form)
        self.ProjectAddressBtn.setGeometry(QtCore.QRect(230, 250, 181, 46))
        self.ProjectAddressBtn.setObjectName("ProjectAddressBtn")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(80, 370, 108, 24))
        self.label_3.setObjectName("label_3")
        self.AddFolderBtn = QtWidgets.QPushButton(Form)
        self.AddFolderBtn.setGeometry(QtCore.QRect(780, 360, 91, 46))
        self.AddFolderBtn.setObjectName("AddFolderBtn")
        self.FolderListWidget = QtWidgets.QListWidget(Form)
        self.FolderListWidget.setGeometry(QtCore.QRect(230, 360, 531, 341))
        self.FolderListWidget.setObjectName("FolderListWidget")
        self.SubFolderBtn = QtWidgets.QPushButton(Form)
        self.SubFolderBtn.setGeometry(QtCore.QRect(780, 420, 91, 46))
        self.SubFolderBtn.setObjectName("SubFolderBtn")
        self.OKBtn = QtWidgets.QPushButton(Form)
        self.OKBtn.setGeometry(QtCore.QRect(770, 720, 150, 46))
        self.OKBtn.setObjectName("OKBtn")
        self.OKBtn_2 = QtWidgets.QPushButton(Form)
        self.OKBtn_2.setGeometry(QtCore.QRect(940, 720, 150, 46))
        self.OKBtn_2.setObjectName("OKBtn_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "项目名称："))
        self.label_2.setText(_translate("Form", "项目地址："))
        self.ProjectAddressBtn.setText(_translate("Form", "选择项目地址"))
        self.label_3.setText(_translate("Form", "添加资源："))
        self.AddFolderBtn.setText(_translate("Form", "+"))
        self.SubFolderBtn.setText(_translate("Form", "-"))
        self.OKBtn.setText(_translate("Form", "确定"))
        self.OKBtn_2.setText(_translate("Form", "取消"))
